### ISSUE TITLE
Be able to specify directory

### ISSUE THREAD

**Issue by svile** [TechHawk/SuperSettings#1]
Hey this is a great plugin and just what i was looking for! So thanks for that first!

However, if you have many SublimeText plugins with different configuration in all of them, keeping it all (in this case) in the root directory of your project can get out of hand. Would you consider adding the following step to the current settings discovery workflow:

"If no *.sublime-settings are found in e.g. <current directory>/*.sublime-settings, do a second check for <current directory>/sublime-settings/*.sublime-settings"

The rest of the current behavior however should be preserved - e.g. once settings are discovered, apply them to all directories and subdirectories and any settings lower in the directory tree take precedence.

If you're willing to add such a functionality, but don't have the time, i can submit a pull request in the next few days.

**Comment by TechHawk** [comment]
Thank you very much for your feedback, I am glad you like it!

I do not fully understand the described scenario. Do you have settings files from other Sublime Text plugins in the root directory of your project? Or are you referring to having too many *SuperSettings* settings files in the root of your project? Could you give me an example from one of your projects?

**Comment by svile** [comment]
It is not really that much of a problem to be honest. Right now I have only two:
```
--- project
    \--- docs
    \--- src
    \--- Anaconda.sublime-settings
    \--- Preferences.sublime-settings
```

But I generally like to keep things organized and can see how this list can get longer as I find more useful packages. It would be nice to be able to do something similar to:

```
\--- project
     \--- docs
     \--- src
     \--- sublime-settings
          \--- Anaconda.sublime-settings
          \--- Preferences.sublime-settings
```

**Comment by svile** [comment]
So yes, in a way - having too many settings in the root of the project

**Comment by TechHawk** [comment]
I understand now, thank you for the clarification!

I have decided to not implement this functionality at the moment to keep the logic simple. While it certainly can be useful to not have dozens of configuration files in the root of the project, I would like to see whether this really is a problem in the long run and whether others will request a similar feature.

Feel free to let me know if you end up with a lot of settings files in the future.
